spring:
  application:
    name: eureka-peer
server:
  port: 10000
eureka:
  instance:
    hostname: dev
    instance-id: dev
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10000/eureka/ #,http://localhost:10001/eureka/,http://localhost:10002/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000